# Generated by Django 4.0.4 on 2024-06-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='pasport_book',
            name='article',
            field=models.IntegerField(verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='publishing_house',
            name='agent_firstname',
            field=models.CharField(max_length=255, verbose_name='Фамилия представителя'),
        ),
        migrations.AlterField(
            model_name='publishing_house',
            name='agent_name',
            field=models.CharField(max_length=255, verbose_name='Имя представителя'),
        ),
        migrations.AlterField(
            model_name='publishing_house',
            name='agent_surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество представителя'),
        ),
        migrations.AlterField(
            model_name='publishing_house',
            name='telephone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='publishing_house',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название издательства'),
        ),
    ]
