# Generated by Django 4.0.10 on 2024-06-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libary', '0002_alter_books_name_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libary.publishing_house', verbose_name='Издательство'),
        ),
    ]
