# Generated by Django 4.0.10 on 2024-06-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libary', '0003_alter_books_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=255, verbose_name='Имя автора')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия автора')),
                ('author_surname', models.CharField(max_length=255, verbose_name='Отчество автора')),
            ],
            options={
                'verbose_name': 'Имя автора',
                'verbose_name_plural': 'Имена авторов',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='libary.author', verbose_name='Автор книги'),
        ),
    ]
