# Generated by Django 4.0.10 on 2024-06-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libary', '0004_author_books_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishing_house',
            name='agent_firstname',
        ),
        migrations.AddField(
            model_name='publishing_house',
            name='agent_secondname',
            field=models.CharField(default=1, max_length=255, verbose_name='Имя представителя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publishing_house',
            name='agent_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия представителя'),
        ),
    ]
