# Generated by Django 4.0.10 on 2024-06-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libary', '0005_remove_publishing_house_agent_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishing_house',
            options={'permissions': [('change_only_telephone', 'Можно изменять только телефон')], 'verbose_name': 'Издательство', 'verbose_name_plural': 'Издательства'},
        ),
    ]
