version: "3.11"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/code/staticfiles  # Монтируем статику
    depends_on:
      - web

  web:
    build: .
    command: ["/bin/sh", "-c", "chmod +x /code/wait-for-it.sh && /code/wait-for-it.sh db:5432 -- python manage.py collectstatic --noinput && uwsgi --ini /code/uwsgi.ini"]
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles  # Монтируем статику
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
  staticfiles:  # Объявляем volume для статики