# Generated by Django 4.0.10 on 2024-07-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_pos_supply_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Поставщика', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
