# Generated by Django 4.0.10 on 2024-07-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parametr',
            field=models.ManyToManyField(default='Без параметра', through='shop.Pos_parametr', to='shop.parametr', verbose_name='Характеристики товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, default='Без тега', to='shop.tag', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(max_length=5, verbose_name='Рейтинг'),
        ),
    ]
